name: Deploy FastAPI to Azure App Service with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: fastapi-backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        echo MONGO_USER = ${{ secrets.MONGO_USER }} >> .env
        echo MONGO_PASSWORD = ${{ secrets.MONGO_PASSWORD }} >> .env
        echo MONGO_CLUSTER = ${{ secrets.MONGO_CLUSTER }} >> .env

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Docker Image
      run: |
        docker build --build-arg MONGO_USER=${{ secrets.MONGO_USER }} \
                      --build-arg MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
                      --build-arg MONGO_CLUSTER=${{ secrets.MONGO_CLUSTER }} \
                      -t fastapi-backend:latest .
        docker tag fastapi-backend:latest ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/fastapi-backend:latest

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name ${{ secrets.AZURE_ACR_NAME }}

    - name: Push Docker Image to Azure Container Registry
      run: |
        docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/fastapi-backend:latest

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        slot-name: production
        images: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/fastapi-backend:latest
